language: node_js
node_js:
  - 12

services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - stage: Test
      name: 'ESLint'
      script: npm run lint
    - name: 'Jesting Unit'
      script: npm test:unit
    - name: 'Jesting Integration'
      script: docker-compose run api npm test:integration
