language: node_js
node_js:
  - 12

branches:
  only:
    - master

jobs:
  include:
    - stage: Test
      name: 'ESLint'
      script: npm run lint
    - # stage name not required, will continue to use `Test`
      name: 'Jest Testing'
      script: npm test
