version: '3.8'

services:
  db:
    image: bagelbits/5e-database:latest

  cache:
    image: redis:6.2.5

  api:
    environment:
      MONGODB_URI: mongodb://db/5e-database
      REDIS_HOST: cache
      REDIS_PORT: 6379
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - cache
