get:
  summary: Get all endpoint urls.
  tags:
    - Base
  responses:
    "200":
      description: "OK"
      content:
        application/json:
          schema:
            type: object
            additionalProperties:
              type: string
