get:
  summary: Get all resource URLs.
  description: Making a request to the API's base URL returns an object containing available endpoints.
  tags:
    - Base
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            additionalProperties:
              type: string
          example:
            ability-scores: "/api/ability-scores"
            alignments: "/api/alignments"
            backgrounds: "/api/backgrounds"
            classes: "/api/classes"
            conditions: "/api/conditions"
            damage-types: "/api/damage-types"
            equipment-categories: "/api/equipment-categories"
            equipment: "/api/equipment"
            feats: "/api/feats"
            features: "/api/features"
            languages: "/api/languages"
            magic-items: "/api/magic-items"
            magic-schools: "/api/magic-schools"
            monsters: "/api/monsters"
            proficiencies: "/api/proficiencies"
            races: "/api/races"
            rules: "/api/rules"
            rule-sections: "/api/rule-sections"
            skills: "/api/skills"
            spells: "/api/spells"
            subclasses: "/api/subclasses"
            subraces: "/api/subraces"
            traits: "/api/traits"
            weapon-properties: "/api/weapon-properties"
