services:
  db:
    image: 5e-database-local
    build:
      context: ../..
      dockerfile: packages/5e-database/Dockerfile
    ports:
      - '27017:27017'
    # The image's 30s default interval stalls `--wait`.
    healthcheck:
      interval: 2s

  cache:
    image: redis:6.2.5
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s

  api:
    environment:
      MONGODB_URI: mongodb://db/5e-database
      REDIS_URL: redis://cache:6379
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
      - cache
