name: Database CI

on:
  workflow_call:

jobs:
  build:
    name: Lint and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/5e-database
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # @v7.0.0
      - uses: ./.github/actions/setup-node-pnpm
      - run: pnpm run lint
      - run: pnpm run build:ts
      - run: pnpm run test
