name: Infrastructure CI

on:
  workflow_call:

jobs:
  build:
    name: Build, test and synth
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/infrastructure
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # @v7.0.0
      - uses: ./.github/actions/setup-node-pnpm
      - run: pnpm build
      - run: pnpm test
      - run: pnpm cdk synth --quiet
